In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df = pd.read_csv("/content/drive/MyDrive/AI and ML/Week8/trumptweets_small.csv")
df.head()

,id,link,content,date,retweets,favorites,mentions,hashtags,geo
0,1698308935,https://twitter.com/realDonaldTrump/status/169...,Be sure to tune in and watch Donald Trump on L...,2009-05-04 20:54:25,500,868,NaN,NaN,NaN
1,1701461182,https://twitter.com/realDonaldTrump/status/170...,Donald Trump will be appearing on The View tom...,2009-05-05 03:00:10,33,273,NaN,NaN,NaN
2,1737479987,https://twitter.com/realDonaldTrump/status/173...,Donald Trump reads Top Ten Financial Tips on L...,2009-05-08 15:38:08,12,18,NaN,NaN,NaN
3,1741160716,https://twitter.com/realDonaldTrump/status/174...,New Blog Post: Celebrity Apprentice Finale and...,2009-05-08 22:40:15,11,24,NaN,NaN,NaN
4,1773561338,https://twitter.com/realDonaldTrump/status/177...,"""My persona will never be that of a wallflower...",2009-05-12 16:07:28,1399,1965,NaN,NaN,NaN

In [4]:
import re
def remove_urls(text):
  """
  This function will try to remove URL present in out dataset and replace it with space using regex library.
  Input Args:
  text: strings of text that may contain URLs.
  Output Args:
  text: URLs replaces with text
  """
  url_pattern = re.compile(r'https?://\S+|www\.\S+')
  return url_pattern.sub(r'', text)

In [5]:
text = " Click on this link to open facebook https://www.facebook.com/"
text_url = remove_urls(text)
text_url

' Click on this link to open facebook '

In [7]:
text_no_url = df["content"].apply(remove_urls)

Remove emojis

In [8]:
def remove_emoji(string):
  """
  This function will replace the emoji in string with whitespace
  """
  emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
  return emoji_pattern.sub(r' ', string)

In [9]:
test_string = "Helloaavvvv 👋🏾👋🏾👋🏾👋🏾👋🏾👋🏾👋🏾👋🏾, still on up for the movie???  #MovieNight #friday #🍱"
no_emoji = remove_emoji(test_string)
no_emoji

'Helloaavvvv  , still on up for the movie???  #MovieNight #friday # '

In [10]:
text_no_emoji = df["content"].apply(remove_emoji)

Remove unwanted characters

In [11]:
def remove_unwanted_characters(document):
    """
    Removes unnecessary characters and formatting from text data.

    This includes user mentions, hashtags, punctuation,
    emojis, and extra whitespace.

    Parameters:
        document (str): Input text to be cleaned.

    Returns:
        str: Cleaned text document.
    """

    # Remove user mentions (e.g., @username)
    document = re.sub(r"@[A-Za-z0-9_]+", " ", document)

    # Remove hashtags
    document = re.sub(r"#[A-Za-z0-9_]+", "", document)

    # Remove punctuation and special characters
    document = re.sub(r"[^0-9A-Za-z ]", "", document)

    # Remove emojis
    document = remove_emoji(document)

    # Replace multiple spaces with a single space
    document = re.sub(r"\s+", " ", document)

    return document.strip()

In [12]:
# Test:
cleaned_string = remove_unwanted_characters(test_string)
cleaned_string

'Helloaavvvv still on up for the movie'

In [13]:
text_removed_unwanted = df["content"].apply(remove_unwanted_characters)

## Tokenizations

In [18]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [19]:
IN = "He refused to continue after the first brave attempt, because the experience had taken something from his spirit."

OUT = word_tokenize(IN)

OUT

['He',
 'refused',
 'to',
 'continue',
 'after',
 'the',
 'first',
 'brave',
 'attempt',
 ',',
 'because',
 'the',
 'experience',
 'had',
 'taken',
 'something',
 'from',
 'his',
 'spirit',
 '.']

### Remove Punctutations:

In [20]:
from nltk.tokenize import RegexpTokenizer

def remove_punct(text):
    """
    Removes punctuation from text using regex-based tokenization.

    Parameters:
        text (str): Input raw text.

    Returns:
        list: Tokenized text containing only alphanumeric words.
    """

    # Tokenizer that keeps only words (removes punctuation)
    tokenizer = RegexpTokenizer(r"\w+")

    # Tokenize directly from string input
    tokens = tokenizer.tokenize(text)

    return tokens

In [21]:
# Test input with punctuation
text_punctuation = "He did not try to navigate: after the!!!! first bold flight, for,,,,, the reaction!!!!had taken??????? something out of his soul."

# Original text
print(text_punctuation)
print("--------------------------------------------------")

# Tokenize using NLTK
text_punc_token = word_tokenize(text_punctuation)
print(text_punc_token)
print("--------------------------------------------------")

# Clean punctuation using custom function (expects string, not list)
text_clean = remove_punct(text_punctuation)
print(text_clean)

He did not try to navigate: after the!!!! first bold flight, for,,,,, the reaction!!!!had taken??????? something out of his soul.
--------------------------------------------------
['He', 'did', 'not', 'try', 'to', 'navigate', ':', 'after', 'the', '!', '!', '!', '!', 'first', 'bold', 'flight', ',', 'for', ',', ',', ',', ',', ',', 'the', 'reaction', '!', '!', '!', '!', 'had', 'taken', '?', '?', '?', '?', '?', '?', '?', 'something', 'out', 'of', 'his', 'soul', '.']
--------------------------------------------------
['He', 'did', 'not', 'try', 'to', 'navigate', 'after', 'the', 'first', 'bold', 'flight', 'for', 'the', 'reaction', 'had', 'taken', 'something', 'out', 'of', 'his', 'soul']

### Remove StopWord:

In [22]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
stop_words = set(stopwords.words('english'))
custom_stopwords = ['@', 'RT']
stop_words.update(custom_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [23]:
def remove_stopwords(text_tokens):
    """
    Removes stopwords from a list of tokenized words.

    Parameters:
        text_tokens (list): List of word tokens.

    Returns:
        list: Tokens with stopwords removed.
    """

    result_tokens = []

    # Filter out stopwords
    for token in text_tokens:
        if token not in stop_words:
            result_tokens.append(token)

    return result_tokens

In [24]:
# Test input tokens
test_inputs = [
    'He', 'did', 'not', 'try', 'to', 'navigate', 'after', 'the',
    'first', 'bold', 'flight', ',', 'for', 'the', 'reaction',
    'had', 'taken', 'something', 'out', 'of', 'his', 'soul', '.'
]

# Display original tokens
print("Original tokens:")
print(test_inputs)

# Remove stopwords
tokens_without_stopwords = remove_stopwords(test_inputs)

# Display cleaned tokens
print("\nTokens without stopwords:")
print(tokens_without_stopwords)

Original tokens:
['He', 'did', 'not', 'try', 'to', 'navigate', 'after', 'the', 'first', 'bold', 'flight', ',', 'for', 'the', 'reaction', 'had', 'taken', 'something', 'out', 'of', 'his', 'soul', '.']

Tokens without stopwords:
['He', 'try', 'navigate', 'first', 'bold', 'flight', ',', 'reaction', 'taken', 'something', 'soul', '.']

## Text Normalization:

### Lemmatization:

In [25]:
from nltk.stem import WordNetLemmatizer
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')


def lemmatization(token_text):
    """
    Performs lemmatization on a list of tokens.

    Parameters:
        token_text (list): List of word tokens.

    Returns:
        list: Lemmatized tokens.
    """

    lemmatizer = WordNetLemmatizer()

    # Lemmatize each token (defaulting to verb form)
    lemmatized_tokens = [
        lemmatizer.lemmatize(token, pos='v') for token in token_text
    ]

    return lemmatized_tokens

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

In [26]:
lemmatization("They were deciding whether to walk or swim".split())

['They', 'be', 'decide', 'whether', 'to', 'walk', 'or', 'swim']

### Stemming:

In [27]:
from nltk.stem import PorterStemmer

def stemming(token_text):
    """
    Applies Porter Stemming to a list of tokens.

    Parameters:
        token_text (list): List of word tokens.

    Returns:
        list: Stemmed tokens.
    """

    porter = PorterStemmer()
    stemmed_tokens = []

    for word in token_text:
        stemmed_tokens.append(porter.stem(word))

    return stemmed_tokens

In [28]:
# Test input tokens
print("---------------------------- INPUT TOKENS ----------------------------")

token_text_test = [
    'Connects', 'Connecting', 'Connections',
    'Connected', 'Connection', 'Connectings', 'Connect'
]

print(token_text_test)

# Lemmatization output
print("\n-------------------------- LEMMATIZED TOKENS --------------------------")
lemma_tokens = lemmatization(token_text_test)
print(lemma_tokens)

# Stemming output
print("\n---------------------------- STEMMED TOKENS ----------------------------")
stemmed_tokens = stemming(token_text_test)
print(stemmed_tokens)

---------------------------- INPUT TOKENS ----------------------------
['Connects', 'Connecting', 'Connections', 'Connected', 'Connection', 'Connectings', 'Connect']

-------------------------- LEMMATIZED TOKENS --------------------------
['Connects', 'Connecting', 'Connections', 'Connected', 'Connection', 'Connectings', 'Connect']

---------------------------- STEMMED TOKENS ----------------------------
['connect', 'connect', 'connect', 'connect', 'connect', 'connect', 'connect']

### Lower order

In [29]:
def lower_order(text):
    """
    Converts input text to lowercase.

    Parameters:
        text (str): Input text string.

    Returns:
        str: Lowercased text.
    """

    lower_text = text.lower()
    return lower_text


# Test case
sample_text = "This Is some Normalized TEXT"
sample_lower = lower_order(sample_text)

print(sample_lower)

this is some normalized text

## Create Input Text Pipeline

EXERCISE-1

In [31]:
data = pd.read_csv("/content/drive/MyDrive/AI and ML/Week8/trumptweets_small.csv", encoding="ISO-8859-1")
data.head()

,id,link,content,date,retweets,favorites,mentions,hashtags,geo
0,1698308935,https://twitter.com/realDonaldTrump/status/169...,Be sure to tune in and watch Donald Trump on L...,2009-05-04 20:54:25,500,868,NaN,NaN,NaN
1,1701461182,https://twitter.com/realDonaldTrump/status/170...,Donald Trump will be appearing on The View tom...,2009-05-05 03:00:10,33,273,NaN,NaN,NaN
2,1737479987,https://twitter.com/realDonaldTrump/status/173...,Donald Trump reads Top Ten Financial Tips on L...,2009-05-08 15:38:08,12,18,NaN,NaN,NaN
3,1741160716,https://twitter.com/realDonaldTrump/status/174...,New Blog Post: Celebrity Apprentice Finale and...,2009-05-08 22:40:15,11,24,NaN,NaN,NaN
4,1773561338,https://twitter.com/realDonaldTrump/status/177...,"""My persona will never be that of a wallflower...",2009-05-12 16:07:28,1399,1965,NaN,NaN,NaN

In [32]:
data_cleaning = data["content"].dropna()

In [33]:
data_cleaning[0]

'Be sure to tune in and watch Donald Trump on Late Night with David Letterman as he presents the Top Ten List tonight!'

In [34]:
import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer

# Download NLTK resources
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [35]:
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer


def lower_order(text):
    """Convert text to lowercase."""
    return text.lower()


def remove_urls(text):
    """Remove URLs from text."""
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub('', text)


def remove_emoji(text):
    """Remove emojis from text."""
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"
        u"\U0001F300-\U0001F5FF"
        u"\U0001F680-\U0001F6FF"
        u"\U0001F1E0-\U0001F1FF"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(' ', text)


def remove_unwanted_characters(document):
    """
    Removes mentions, hashtags, punctuation, emojis, and extra whitespace.
    """
    document = re.sub(r"@[A-Za-z0-9_]+", " ", document)
    document = re.sub(r"#[A-Za-z0-9_]+", "", document)
    document = re.sub(r"[^0-9A-Za-z ]", "", document)

    document = remove_emoji(document)

    # Normalize whitespace (fixes multiple spaces properly)
    document = re.sub(r"\s+", " ", document)

    return document.strip()


def stemming(text):
    """Apply Porter Stemming to tokenized text."""
    porter = PorterStemmer()
    return [porter.stem(word) for word in text]


def lemmatization(text):
    """Apply WordNet Lemmatization to tokenized text."""
    lemmatizer = WordNetLemmatizer()
    return [lemmatizer.lemmatize(word) for word in text]

In [39]:
def text_cleaning_pipeline(dataset, rule="lemmatize"):
    """
    Preprocess text data through a series of cleaning steps.

    Args:
        dataset (str): Input text to be cleaned.
        rule (str): Either 'lemmatize' or 'stem' to choose normalization method.

    Returns:
        str: Cleaned and processed text.
    """
    # Handle non-string or NaN input
    if not isinstance(dataset, str):
        return ""

    # Convert to lowercase
    data = lower_order(dataset)

    # Remove URLs
    data = remove_urls(data)

    # Remove emojis
    data = remove_emoji(data)

    # Remove other unwanted characters (mentions, hashtags, punctuation)
    data = remove_unwanted_characters(data)

    # Tokenize
    tokens = word_tokenize(data)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]

    # Apply lemmatization or stemming
    if rule == "lemmatize":
        tokens = lemmatization(tokens)
    elif rule == "stem":
        tokens = stemming(tokens)
    else:
        print("Pick between lemmatize or stem")
        return ""

    # Join tokens back into a string
    return " ".join(tokens)

In [40]:
sample = "Hello @gabe_flomo 👋🏾, I still want us to hit that new sushi spot??? LMK when you're free cuz I can't go this or next weekend since I'll be swimming!!! #sushiBros #rawFish #🍱"
print(text_cleaning_pipeline(sample))

hello still want u hit new sushi spot lmk youre free cuz cant go next weekend since ill swimming

In [41]:
test = data["content"][0]
print("\nOriginal Tweet:", test)
print("Cleaned Tweet:", text_cleaning_pipeline(test))

Original Tweet: Be sure to tune in and watch Donald Trump on Late Night with David Letterman as he presents the Top Ten List tonight!
Cleaned Tweet: sure tune watch donald trump late night david letterman present top ten list tonight

In [42]:
print(text_cleaning_pipeline(test))

sure tune watch donald trump late night david letterman present top ten list tonight

In [43]:
cleaned_tokens = data["content"].apply(lambda dataset: text_cleaning_pipeline(dataset))

In [44]:
cleaned_tokens[0]

'sure tune watch donald trump late night david letterman present top ten list tonight'